services:
  mcp_massive:
    build: .
    volumes:
      - .:/app
    container_name: mcp_massive_server
    environment:
      - MASSIVE_API_KEY=${MASSIVE_API_KEY}
      - MCP_TRANSPORT=streamable-http
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
